# Dia 38 - Aluguel de carro (dias + km)
dias = int(input('Quantos dias alugados? '))
km = float(input('Quantos km rodados? '))
pago = (dias * 60) + (km * 0.15)
print(f'o total a pagar é de R${pago:.2f}')
